First_Django/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from inventory import views
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url, include
from django.contrib.auth.views import (password_reset, password_reset_done,
                                      password_reset_confirm, password_reset_complete, password_change,
                                      password_change_done,)

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^item/(?P<id>\d+)/', views.item_detail, name="item_detail"),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/login/$', views.login),
    url(r'^accounts/auth/$', views.auth_view),
    url(r'^accounts/logout/$', views.logout),
    url(r'^accounts/loggedin/$', views.loggedin),
    url(r'^accounts/invalid/$', views.invalid_login),
    url(r'^accounts/register/$', views.register_user),
    url(r'^accounts/register_check/$', views.register_check),
    url(r'^accounts/register_verification/$', views.register_verification),
    #url(r'^items/add_comment/(?P<id>\d+)/$', views.add_comment),
    url(r'^profile/$', views.profile),
    url(r'^edit_profile/$', views.edit_profile),
    url(r'^create/$', views.create),
    url(r'^reset-password/$', password_reset, name='reset-password'),
    url(r'^reset-password/done/$', password_reset_done, name= 'password_reset_done'),
    url(r'^reset-password/complete/$', password_reset_complete, name= 'password_reset_complete'),
    url(r'^reset-password/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$',
        password_reset_confirm, name= 'password_reset_confirm'),
    url(r'^password/change/$', password_change, name='password_change'),
    url(r'^password/change/done/$', password_change_done, name='password_change_done'),
]
if settings.DEBUG:

    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

inventory/models.py
from django.db import models


class Item(models.Model):
    title = models.CharField(max_length=200)
    content = models.TextField()
    image = models.FileField(null=True,blank=True)
    updated = models.DateTimeField(auto_now=True, auto_now_add=False)
    created = models.DateTimeField(auto_now=False, auto_now_add=True)
    author = models.CharField(max_length=200, null=True)

def __str__(self):
    return '%s' % (self.title)


class Comment(models.Model):
    name = models.CharField(max_length=200)
    body = models.TextField()
    pub_date = models.DateTimeField('date published')
    itemz = models.ForeignKey(Item)

    def __str__(self):
        return '%s' % (self.name)

inventory/forms.py
import urllib
import urllib2
import json

from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.conf import settings
from django.utils.translation import ugettext as _
from django.forms import ValidationError

from models import Comment, Item


class MyRegistrationForm(UserCreationForm):
    email = forms.EmailField(required=True)
    first_name = forms.CharField(required=True)
    last_name = forms.CharField(required=True)

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2',)
        staff_status = True

    # fff

    def __init__(self, *args, **kwargs):
        # make the request object available to the form object
        self.request = kwargs.pop('request', None)
        super(MyRegistrationForm, self).__init__(*args, **kwargs)

    def clean(self):
        super(MyRegistrationForm, self).clean()
        # test the google recaptcha
        url = "https://www.google.com/recaptcha/api/siteverify"
        values = {
            'secret': settings.GOOGLE_RECAPTCHA_SECRET_KEY,
            'response': self.request.POST.get(u'g-recaptcha-response', None),
            'remoteip': self.request.META.get("REMOTE_ADDR", None),
        }
        data = urllib.urlencode(values)
        req = urllib2.Request(url, data)
        response = urllib2.urlopen(req)
        result = json.loads(response.read())

        # result["success"] will be True on a success
        if not result["success"]:
            raise forms.ValidationError(_(u'Only humans are allowed to submit this form.'))
        return self.cleaned_data

    # gggg
    def clean_password(self):
        password = self.cleaned_data.get('password1')
        if len(password) < 8:
            raise ValidationError('Password too short')
        return password

    def save(self, commit=True):
        user = super(MyRegistrationForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        commit = self.clean_password()
        if commit:
            user.save()
        return user


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('body',)


class EditProfileForm(forms.ModelForm):
    first_name = forms.CharField()
    last_name = forms.CharField()
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email']


class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ('title', 'image', 'content',)

inventory/views.py
from django.shortcuts import render, render_to_response
from django.http import Http404, HttpResponseRedirect
from django.contrib import auth
from django.template.context_processors import csrf
from django.utils import timezone
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import render
from django.core.mail import EmailMessage

from inventory.models import Item
from .forms import MyRegistrationForm, CommentForm, EditProfileForm,ItemForm


def index(request):
    items_list = Item.objects.all()
    #using pagination
    query = request.GET.get("s")
    if query:
        items_list=items_list.filter(title__icontains = query)
    paginator = Paginator(items_list, 10) # Show 10 contacts per page

    page = request.GET.get('page')
    try:
        items = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        items = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        items = paginator.page(paginator.num_pages)

    return render(request, 'inventory/index.html', {'items': items, 'id': id})


def item_detail(request, id):
    try:
        item = Item.objects.get(id=id)
    except Item.DoesNotExist:
        raise Http404("Item doesnt exist")
    if request.method == "POST":
        f = CommentForm(request.POST)
        if f.is_valid():
            c = f.save(commit=False)
            c.pub_date = timezone.now()
            c.name = request.user
            c.itemz = item
            c.save()
            return HttpResponseRedirect('/item/%s/' % id)

    else:
        f = CommentForm()
    args = {}
    args.update(csrf(request))
    args['itemz'] = item
    args['form'] = f
    args['user'] = request.user
    args['id'] = id
    args['item'] = item

    return render(request, 'inventory/item_detail.html',args)


def login(request):
    c = {}
    c.update(csrf(request))
    return render_to_response('login.html', c)


def auth_view(request):
    username = request.POST.get('username', '')
    password = request.POST.get('password', '')
    user = auth.authenticate(username=username, password=password)
    if user is not None:
        auth.login(request, user)
        return HttpResponseRedirect('/')
    else:
        return HttpResponseRedirect('/accounts/invalid')


def loggedin(request):
    return render_to_response('loggedin.html', {'full_name:request.user.username'})


def invalid_login(request):
    return render_to_response("invalid_login.html")


def logout(request):
    auth.logout(request)
    return render_to_response('logout.html')


def register_user(request):
    if request.method == 'POST':
        form = MyRegistrationForm(request.POST,request=request)
        if form.is_valid():
            # form.save()
            save_it= form.save()
            email = save_it.email
            send_email(request, email)
            return HttpResponseRedirect('/accounts/register_check')

    args = {}
    args.update(csrf(request))
    args['form'] = MyRegistrationForm()
    return render_to_response('register.html', args)

def send_email(request, email):
    msg = EmailMessage('Account verification',
                       'Click the below link to activate your account.\n 127.0.0.1:8000/accounts/register_verification/ ', to=[email])
    msg.send()

# def send_email(request, email):
#     msg = EmailMessage('Account verification',
#                        'Click the below link to activate your account.\n mighty-reef-46503.herokuapp.com/accounts/register_verification/ ', to=[email])
#     msg.send()


def register_check(request):
    return render_to_response('register_check.html',{'user': request.user})

def register_verification(request):
    return render_to_response('account_verified.html')


def add_comment(request, id):
    a = Item.objects.get(id=id)

    if request.method == "POST":
        f = CommentForm(request.POST)
        if f.is_valid():
            c = f.save(commit=False)
            c.pub_date = timezone.now()
            c.name = request.user
            c.itemz = a
            c.save()
            return HttpResponseRedirect('/item/%s/' % id)

    else:
        f = CommentForm()
    args = {}
    args.update(csrf(request))
    args['itemz'] = a
    args['form'] = f
    args['user'] = request.user
    args['id'] = id
    return render_to_response("add_comment.html", args)


def profile(request):
    a = request.user
    c = {}
    c['user'] = a
    c['name'] = a.username
    c['email'] = a.email
    c['firstname'] = a.first_name
    c['lastname'] = a.last_name
    return render_to_response('profile.html', c)


def edit_profile(request):
    user = request.user
    form = EditProfileForm(request.POST)
    if request.method == 'POST':
        if form.is_valid():
            user.first_name = request.POST['first_name']
            user.last_name = request.POST['last_name']
            user.email = request.POST['email']
            user.save()
            return HttpResponseRedirect('/profile/')
    d = {}
    d['form'] = EditProfileForm()
    return render(request, "edit_profile.html", d)

def create(request):
    if request.POST:
        form = ItemForm(request.POST , request.FILES or None)
        if form.is_valid():
            # form.save()
            f=form.save(commit=False)
            f.author = request.user
            f.save()
            return HttpResponseRedirect('/')
    else:
        form = ItemForm()

    args = {}
    args.update(csrf(request))
    args['form'] = form
    # if request.user.is_authenticated():
    args['user'] = request.user
    return render_to_response('create_item.html', args)

First_Django/templates/inventory/index.html
{% extends "base.html" %}
{% block nav %}
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      </div>
      <div class="collapse navbar-collapse" id="myNavbar">
    <ul class="nav navbar-nav">
      <li title="Home"><a href="#"><span class="glyphicon glyphicon-home"></span></a></li>
        {% if user.is_authenticated %}
        <li title="Create"><a href="create">Create Blog</a></li>
         {% endif %}
    </ul>
    <ul class="nav navbar-nav navbar-right">
        {% if not user.is_authenticated %}
      <li title="Login"><a href='accounts/login'>Login</a></li>
           <li title="Forgot Password"><a href='reset-password/'>ForgotPassword</a></li>
        <li title="Register"><a href="accounts/register/">Register</a></li>
     {% endif %}
        {% if user.is_authenticated %}
        <li title="Edit Profile"><a href="/edit_profile/">Edit Profile</a></li>
        <li title="logout"><a href="accounts/logout/">Logout</a></li>
        {% endif %}
       </ul>
  </div>
  </div>
    </nav>
{% endblock %}


{% block content %}
    <div class='col-sm-6 col-sm-offset-3'>

	<h3>BLOGS</h3>
    <form method='GET' action=''>
<input type='text' name='s' placeholder='Search posts' value='{{ request.GET.s }}'/>
<input type='submit' value='Search' />
</form>

{% for item in items %}
    <div class="row">
   <div class="col-sm-12">
     <div class="thumbnail">
        {% if item.image %}
         <img src='{{ item.image.url }}' class='img-responsive' />
        {% endif %}
      <div class="caption">
        <h3><a href='{% url 'item_detail' item.id %}'>{{ item.title }}</a></h3>
      <h5><small>{{ item.created }}</small></h5>
        {% if item.author %}<p>Author: {{ item.author }}</p>{% endif %}
        <p>{{ item.content|linebreaks|truncatechars:120 }}</p>
        <p><a href="{% url 'item_detail' item.id %}" class="btn btn-default" role="button">View</a></p>
      </div>
    </div>
  </div>
    </div>
    {% endfor %}





    <div class="pagination">
    <span class="step-links">
        {% if items.has_previous %}
            <a href="?page={{ items.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ items.number }} of {{ items.paginator.num_pages }}.
        </span>

        {% if items.has_next %}
            <a href="?page={{ items.next_page_number }}">next</a>
        {% endif %}
    </span>
</div>
    </div>

    </div>
{% endblock %}

First_Django/templates/inventory/item_detail.html
{% extends "base.html" %}
{% block content%}
{#    {% load crispy_forms_tags %}#}
	<a href="{% url 'index' %}">Back to Blog list</a>
    <div class='col-sm-6 col-sm-offset-3'>
	<h3>{{ item.title|capfirst }}</h3>
    {% if item.author %}
    <h5>author:{{ item.author }}</h5>
    {%endif %}
    <h4><small>{{ item.created }}</small></h4>
    {%if item.image %}
    <img src="{{ item.image.url }}" class="img-responsive" />
    {% endif %}

  <div class='row'>
<div class='col-sm-12'>

{{ item.content|linebreaks }}

    <br/>

     <h4>Comment</h4>
    {% if user.is_authenticated %}
<form action="" method="post">{% csrf_token %}
<ul>
{#{% crispy form %}#}
{{ form }}
</ul>
        <input type="submit" name="submit" value="Post Comment">
    {% endif %}

</form>
</br>
	{% for c in item.comment_set.all %}
	<p>{{c.name}} : {{c.body}}</p>
	{% endfor %}
	{% if user.is_authenticated %}
		<h6>click <a href="/accounts/logout/">here</a> to logout</h6>
	{% else %}
		<p>Please login to commment</p>
	{% endif %}
{% endblock %}
</div>
</div>
</div>